# Generated by Django 3.2.7 on 2021-09-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_word_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complement',
            name='parent',
        ),
        migrations.AddField(
            model_name='complement',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.word'),
        ),
    ]
